### ISSUE TITLE
README.MD Example 

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#53]
Hi ! 

The latest example that was committed doesn't work:

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openstack.fortnebula.com', port=13808): Max retries exceeded with url: /v1/AUTH_e8fd161dc34c421a979a9e6421f823e9/logs_18/679218/1/gate/tempest-full/88fdd79/controller/logs/dstat-csv_log.txt.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11d085690>: Failed to establish a new connection: [Errno 60] Operation timed out'))

Any idea why ? 

Thank you

**Comment by kwulffert** [comment]
Hi @johnnylousas,
Thank you for reporting the issue.
The example in the documentation is correct, however you hit a new issue.
One of the log providers of the OpenStack infrastructure is not online anymore, so I now added code to handle this type of situation.

**Comment by jlousada315** [comment]
Now, when I run the command I get this multiple times without stopping

Connection time out on https://openstack.fortnebula.com:13808/v1/AUTH_e8fd161dc34c421a979a9e6421f823e9/logs_15/677915/1/gate/tempest-full/be64459/controller/logs/dstat-csv_log.txt.gz
Connection time out on https://openstack.fortnebula.com:13808/v1/AUTH_e8fd161dc34c421a979a9e6421f823e9/logs_15/677915/1/gate/tempest-full/be64459/controller/logs/dstat-csv_log.txt
