### ISSUE TITLE
Find other build names

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#57]
how can I find other projects data available to cache, like tempest-full ? 

Thank you !

**Comment by afrittoli** [comment]
You can find other build names in DB, or you can search for them in the [dashboard](http://status.openstack.org/openstack-health/#/) too, but it may be not obvious which jobs indeed include `dstat` data. Usually integration job that have `devstack` and/or `tempest` in their name are good candidates.

**Comment by afrittoli** [comment]
I'll close this now, feel free to re-open if you have further questions.
