### ISSUE TITLE
tf.logging

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#58]
Hi, 

f.logging.set_verbosity(tf.logging.INFO)
AttributeError: module 'tensorflow' has no attribute 'logging'

This attribute seems to be deprecated in the files: nn_trainer.py , svm_trainer.py and tf_trainer.py. 

To fix this I replaced it for:
tf.compat.v1.logging.set_verbosity(tf.compat.v1.slogging.INFO)

and it worked.

Based on this thread:
https://stackoverflow.com/questions/55318626/module-tensorflow-has-no-attribute-logging

**Comment by afrittoli** [comment]
Thank you for looking into this!
Did you run with the version of tensorflow from the requirements.txt? 
I believe the code should still work with that version, but we can update it nonetheless. Feel free also to propose a PR, since you did the investigation work already ^_^

**Comment by jlousada315** [comment]
Hi, I can attach the corrected version of gather_results.py that fixes this issue or should I commit it ?

**Comment by jlousada315** [comment]
Pull Request sent!

**Comment by kwulffert** [comment]
Thank you João for the PR. It has been merged. I'm closing this issue.
