### ISSUE TITLE
Argument must be string

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#59]
I now have access to the tempest full dataset and the correspondent .json files. 

Now I try to visualize them, by running: ciml-build-dataset --dataset tempest-full --visualize. 

and I get the following exception: 
raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern

**Comment by afrittoli** [comment]
Hi @johnnylousas,  we've been doing most of the visualisation recently in the jupyter notebook - so the `--visualize` option in CIML may be out of date. If you're interested in using it I can have a look, or feel free to propose a PR too.
