### ISSUE TITLE
cache-data nr of entries in data

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#64]
Hi ! 

When caching the tempest-full data, I get around 500 entries for test results and from those the test that fail are very few, around 10. 

How can I know how many test results a dataset has? and how can I collect a bigger dataset ?

Thank you

**Comment by kwulffert** [comment]
Hi @johnnylousas, as log are rotated, when trying to fetch older logs from the log storage, they are unavailable. It will take a time to collect a good amount of data for your experiments. 
Andrea will provide you with information to access to historical data.

**Comment by jlousada315** [comment]
hi @kwulffert,

thank you for the help, the problem is solved.

This issue can now be closed.
